from simple_deck import *
from verbose import *
class CardValue:
    #Dictionary of values of the cards used for the ACBL API.
    trueval = {'c2': 1,
               'c3': 2,
               'c4': 3,
               'c5': 4,
               'c6': 5,
               'c7': 6,
               'c8': 7,
               'c9': 8,
               'ct': 9,
               'cj': 10,
               'cq': 11,
               'ck': 12,
               'ca': 13,
               'd2': 14,
               'd3': 15,
               'd4': 16,
               'd5': 17,
               'd6': 18,
               'd7': 19,
               'd8': 20,
               'd9': 21,
               'dt': 22,
               'dj': 23,
               'dq': 24,
               'dk': 25,
               'da': 26,
               'h2': 27,
               'h3': 28,
               'h4': 29,
               'h5': 30,
               'h6': 31,
               'h7': 32,
               'h8': 33,
               'h9': 34,
               'ht': 35,
               'hj': 36,
               'hq': 37,
               'hk': 38,
               'ha': 39,
               's2': 40,
               's3': 41,
               's4': 42,
               's5': 43,
               's6': 44,
               's7': 45,
               's8': 46,
               's9': 47,
               'st': 48,
               'sj': 49,
               'sq': 50,
               'sk': 51,
               'sa': 52
               }